import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { buildWorker, runtimeInfo } from "./scripts/worker-build.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const runtime = runtimeInfo();

/**
 * `import workerSource from "virtual:tts-worker"` gives the TTS worker as one
 * string of JavaScript. A community plugin ships as a single main.js, so the
 * worker is bundled separately and started from a Blob at runtime.
 */
const inlineWorker = {
	name: "inline-tts-worker",
	setup(build) {
		build.onResolve({ filter: /^virtual:tts-worker$/ }, () => ({
			path: "tts-worker",
			namespace: "inline-worker",
		}));
		build.onLoad({ filter: /.*/, namespace: "inline-worker" }, async () => ({
			contents: `export default ${JSON.stringify(await buildWorker({ minify: prod }))};`,
			loader: "js",
			watchDirs: ["src/worker", "src/shared"],
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
		"@electron/remote",
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		__ORT_VERSION__: JSON.stringify(runtime.version),
		__ORT_WASM_FILE__: JSON.stringify(runtime.file),
		__ORT_WASM_SHA256__: JSON.stringify(runtime.sha256),
		__ORT_WASM_BYTES__: String(runtime.bytes),
	},
	plugins: [inlineWorker],
	loader: {
		".svg": "text",
		".tsx": "tsx",
		".jsx": "jsx",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
